/*
 * @Author: tiantian
 * @Date: 2025-09-01 17:51:27
 * @LastEditTime: 2025-09-03 18:51:58
 * @Description: 
 */
import type { Metadata } from "next";
//谷歌字体
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Dapp",
  description: "Generated by create next dapp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
